### ISSUE TITLE
JavaFxScheduler.getInstance() naming

### ISSUE THREAD

**Issue by dwursteisen** [ReactiveX/RxJavaFX#45]
Hello, 

RxJava gave functional names to Schedulers accessor : `Schedulers.io()`, `Schedulers.computation()`, `Schedulers.newThread()`, ...

RxJavaFX has a technical name for the JavaFX Scheduler accessor : `JavaFxScheduler.getInstance()`. 
Even if you can understand it at the first sight, it can be more revelant to use a fonctional name instead, like : `JavaFxScheduler.ui()`

RxAndroid use the same logic, and hidding the singleton instance though `RxAndroid.mainThread()` : https://github.com/ReactiveX/RxAndroid/blob/1.x/rxandroid/src/main/java/rx/android/schedulers/AndroidSchedulers.java#L56

__TLDR__ : Is renaming `JavaFxScheduler.getInstance()` to `JavaFxScheduler.ui()` can be an option ?

Regards.

**Comment by thomasnield** [comment]
You make a valid argument, and one I haven't really thought of. The more I think about it, it does make sense. I'll implement this as an alias for now, and might deprecate `getInstance()` later. I'll do it later today unless you beat me with a PR.

**Comment by pigelvy** [comment]
Since we can mix the JavaFX "Application thread" with the AWT "Event Dispatch Thread", I think it would be more appropriate to name the method something like jfxUi(). The same could be applied to SwingSchedulers.getInstance() which could become .edt().
Those names wouldn't collide when using static imports, and would convey greater functional meaning about which GUI thread is used.

What do you think?

**Comment by thomasnield** [comment]
@pigelvy welcome back! That does make sense, although `jfxUi()` looks a bit esoteric. Maybe `platform()` since every JavaFX dev has used `Platform.runLater()` at some point? Other candidates at the top of my head:

`platform()`

`fx()`

`fxUi()`

I don't do static importing very often, but I don't think those would clash with other static imports.

**Comment by pigelvy** [comment]
plateform() would indeed be the most meaningful name since every JavaFX user/developer knows (hopefully) about the Platform class.

On the other hand, I've never really understood why they chose the name "Platform". It does not really talk to me since everything and anything can be called a platform. Calling it Framework or YetAnotherSystem would have been the same...

As far as I'm concerned, the following names can do job (until something better):
 - platform() for jDK consistency
 - jfx() for shortness and strong meaning

**Comment by thomasnield** [comment]
I'm biased towards `platform()` due to API consistency, although `jfx()` is fine as well. What do you think @dwursteisen?

**Comment by dwursteisen** [comment]
I think `platform()` better because of the API consistency. An user which know the Java FX threading model will know what it means. But he may have some issues with `jfx()`.

**Comment by thomasnield** [comment]
platform() it is then. I'll implement this later today. It might be a week or so until a new release occurs. Need more changes to warrant that if possible.

**Comment by thomasnield** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Implement `platform()` factory for JavaFxScheduler](https://trello.com/c/FaRoPyGH/1-implement-platform-factory-for-javafxscheduler)

**Comment by thomasnield** [comment]
`platform()` has been implemented. Will include in the next release.
