### ISSUE TITLE
RxJavaFx 2 roadmap

### ISSUE THREAD

**Issue by rguillens** [ReactiveX/RxJavaFX#53]
Is there any plan to migrate Observables to Flowables in version 2 of RxJavaFx, as well as move the maven artifact to the groupId io.reactivex.rxjava2 according to version 2 of RxJava to allow coexistence of versions 1 and 2?

**Comment by thomasnield** [comment]
I added support for Flowables already where it makes sense (primarily through `JavaFxSubscriber` and `RxFlowableTransformer` utility classes). Creating a `Flowable` from UI events, however, does not logically make sense since you cannot programmatically tell a user to slow down emissions. But if you need to turn the `Observable` into a `Flowable`, just call `toFlowable()` and pass the right backpressure strategy to it (this creates a buffer though, and does not truly achieve backpressure). 

Regarding the `groupId`, yes that was a mistake on my part after I released it. As you said, the merit of the new `groupId` is it allows build automation tools to allow both RxJava 1.0 and RxJava 2.0 into a project, and therefore allow RxJava 1.0 projects to migrate slowly to 2.0. I was thinking about changing the `groupId`, and I may in a future release. But I don't know how much demand there is for legacy projects on RxJavaFX 1.0 to migrate gradually to RxJavaFX 2.0. 

I probably will change the `groupId` on the next future release.

**Comment by thomasnield** [comment]
Group ID has been changed.
