### ISSUE TITLE
Not on FX application thread

### ISSUE THREAD

**Issue by khrlimam** [ReactiveX/RxJavaFX#65]
Hey, I got `java.lang.IllegalStateException` when using `Schedulers.newThread()` or `Schedulers.computation()`, and when using `JavaFxScheduler.platform()` got no exception but the process is not asynchronously executed, I have to wait for the process to finish so i can access the UI. Any information, please?

**Comment by thomasnield** [comment]
Can you provide some context please? Since JavaFX elements have to be manipulated on the JavaFX thread, any part of the Observable chain that does so must operate on the JavaFxScheduler. If you need to run a background task, use two observeOn() calls, the first to move it to a newThread(), io(), or computation() scheduler, and a second to move the result to the JavaFxScheduler.

**Comment by thomasnield** [comment]
I haven't heard back awhile on this issue so I'm going to close. Feel free to open if there are further concerns to address.
